version: '3'
services:
  #database
  db.postgresql:
    container_name: db.postgresql
    #name даных - на основе которого будет создан контейнер
    #https://hub.docker.com/_/postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=vitali_ROG
      - POSTGRES_PASSWORD=MESSI15161718
      - POSTGRES_DB=pv111
    ports:
      - "5432:5432"
