version: '3'
services:

  api.gateway:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  webserver:
    build:
      context: ./WebServer
    volumes:
      - ./WebServer:/usr/src/app
    command: sh -c "npm install && npm start"
    container_name: webserver
    environment:
      - SERVER_NAME=webserver

  api.comments:
    build: ./backend/comments
    volumes:
      - ./backend/comments:/usr/src/app
    command: sh -c "npm install && npm start"
    container_name: api_comments
    environment:
      - SERVER_NAME=api.comments

  api.likes:
    build: ./backend/likes
    volumes:
      - ./backend/likes:/usr/src/app
    command: sh -c "npm install && npm start"
    container_name: api_likes
    environment:
      - SERVER_NAME=api.likes

  api.posts:
    build: ./backend/posts
    volumes:
      - ./backend/posts:/usr/src/app
    command: sh -c "npm install && npm start"
    container_name: api_posts
    environment:
      - SERVER_NAME=api.posts

  api.users:
    build: ./backend/users
    volumes:
      - ./backend/users:/usr/src/app
    command: sh -c "npm install && npm start"
    container_name: api_users
    environment:
      - SERVER_NAME=api.users

      #  sunny:
#    build:
#      context: ./WebServer
#    volumes:
#      - ./WebServer:/usr/src/app
#    command: sh -c "npm install && npm start"
#    container_name: sunny
#    environment:
#      - SERVER_NAME=sunny
#
#  jonny:
#    build:
#      context: ./WebServer
#    volumes:
#      - ./WebServer:/usr/src/app
#    command: sh -c "npm install && npm start"
#    container_name: jonny
#    environment:
#      - SERVER_NAME=jonny
#
#    #WAS 1 SERVER
#  webserver:
#    build:
#      context: ./WebServer
#    volumes:
#      - ./WebServer:/usr/src/app
#    command: sh -c "npm install &&  npm start"
#
#    container_name: webserver
#    environment:
#      - SERVER_NAME=webserver
#    ports:
#      - "80:80"


  # database
  db.postgresql:
    container_name: db.postgresql
    image: postgres:16
    environment:
      - POSTGRES_USER=vitali_ROG
      - POSTGRES_PASSWORD=MESSI15161718
      - POSTGRES_DB=pv111
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db.postgresql:/var/lib/postgresql
# inMemoy DB использование кєш и обмена сообще...
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data


# Uncomment the following sections if needed
#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"
#     env_file:
#       - .env

#   mongo-express:
#     image: mongo-express
#     ports:
#       - "8081:8081"
#     env_file:
#       - .env
